/* eslint-disable prettier/prettier */
import {StyleSheet, Dimensions} from 'react-native';
const windowWidth = Dimensions.get('window').width;
export default StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: '#D6EAF8',
    alignItems: 'center',
  },
  container: {
    flex: 1,
    width: windowWidth * 0.92,
    backgroundColor: 'white',
    marginVertical: 15,
    borderRadius: 10,
    //alignItems: 'center',
    //justifyContent: 'center',
  },
  //<--------------product info page css---------------->
  btnContainer: {
    marginTop: 10,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    //backgroundColor: 'purple',
  },
  btnBack: {
    borderWidth: 0.5,
    borderColor: 'black',
    borderRadius: 5,
    width: 200,
    height: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
  },
  productInfoRow: {
    flexDirection: 'row',
    marginHorizontal: 15,
    alignItems: 'center',
    height: windowWidth * 0.4,
    //width: windowWidth - windowWidth * 0.08 - 30,
    //justifyContent: 'center',
    //backgroundColor: 'orange',
  },
  imageContainer: {
    width: windowWidth * 0.25,
    height: windowWidth * 0.25,
    borderWidth: 1,
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
  },
  image: {width: windowWidth * 0.24, height: windowWidth * 0.24},
  productInfoContainer: {
    width: windowWidth - windowWidth * 0.33 - 30,
    height: '100%',
    paddingLeft: 10,
    paddingVertical: 10,
    //backgroundColor: 'green',
  },
  productTextContainerWithButton: {
    flexDirection: 'row',
    height: 25,
    width: '100%',
    //backgroundColor: 'cyan',
    alignItems: 'center',
  },
  productTitleContainer: {
    //backgroundColor: 'yellow',
    height: 25,
    width: '60%',
    //fontSize: 18,
    justifyContent: 'center',
  },
  copyBtnContainer: {
    height: 25, //30
    width: 70,
    //backgroundColor: 'orange',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderRadius: 5,
    borderColor: '#F1948A',
  },
  copyBtn: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  productTextContainer: {
    height: 25,
    width: '100%',
    //backgroundColor: 'blue',
    justifyContent: 'center',
  },
  productText: {
    height: 30,
    fontSize: 14,
  },
  //<--------------SectionList AND FlatList------------->
  //<---------------collapse item css-------------------->
  collapseToggleContainer: {
    borderWidth: 1,
    borderColor: '#F1948A',
    borderRadius: 10,
    marginTop: 10,
    height: 50,
    width: windowWidth - windowWidth * 0.08 - 30,
    //backgroundColor: 'blue',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    justifyContent: 'space-between',
  },
  collapsible: {
    width: windowWidth - windowWidth * 0.08 - 30,
    alignItems: 'center',
  },
  renderItemListContainer: {
    paddingHorizontal: 10,
    width: windowWidth - windowWidth * 0.08 - 30,
    alignItems: 'center',
    justifyContent: 'center',
    //backgroundColor: 'green',
  },
  itemContainer: {
    flexDirection: 'row',
    //backgroundColor: 'cyan',
    height: 30,
    paddingHorizontal: 10,
    //marginBottom: 5,
    width: '100%',
    //width: windowWidth - windowWidth * 0.08 - 30,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  //<-----------------Bottom part------------------->
  //<---------------- inventory request------------->
  viewBtn: {
    marginTop: 20,
    width: windowWidth - windowWidth * 0.08 - 30,
    //backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendBtn: {
    borderWidth: 1,
    borderRadius: 10,
    marginTop: 10,
    height: 50,
    width: '100%',
    borderColor: '#00FF00',
    //backgroundColor: '#00FF00',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  //<-----------------Modal--------------------------->
  modalContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalView: {
    height: 290,
    width: windowWidth - windowWidth * 0.08 - 30,
    alignItems: 'center',
    //justifyContent: 'center',
    backgroundColor: 'white',
    borderRadius: 10,
    borderWidth: 0.5,
  },
  modalTitle: {
    color: 'grey',
    fontSize: 18,
    fontWeight: 'bold',
    marginHorizontal: 10,
  },
  modalDate: {
    borderWidth: 1,
    borderRadius: 10,
    marginTop: 10,
    height: 50,
    width: 240,
    borderColor: '#00FF00',
    //backgroundColor: '#00FF00',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
